### ISSUE TITLE
Please clarify the intent of the GPL license

### ISSUE THREAD

**Issue by jacobian** [briancray/tooltipsy#34]
I note that tooltipsy is licensed under the GPLv2. My assumption from this is that your intent is to require that derivative uses be shared under the same license (i.e. my assumption is that if you'd not wanted share-alike, you might have chosen MIT/BSD-alike). 

I'd like to respect your wishes, but the GPL seems rather unclear as it applies to Javascript. Specifically, the action that triggers the GPL's share-alike requirement is, in GPL parlance, upon "linking". The GPL was written with "link" meaning linking as in compiled source -- e.g., linking `libc` into your program -- not in the HTML-link-to-file sense, so it's hard to make sense of this requirement as it applies to your library. (There's also language about "static" versus "dynamic" linking in the GPL, which is even harder to make sense of in an HTML/JS context.)

So it's unclear to me exactly what my obligations are should I use tooltipsy in my site/apps. I'd really love it if you could clarify what your intent here is -- what actions, in your eyes, trigger the requirement that "linked" works be shared-alike? In particular, there are a few scenarios that seem worth addressing:
1. If I link tooltipsy into some HTML document, must that document be GPL-licensed?
2. If I combine tooltipsy with other Javascript as part of an asset pipeline (e.g. minimize and compile multiple files together, including tooltipsy), must those other files (or the produced minimized output) be GPL-licensed?
3. If I distribute tooltipsy as part of a larger open source web app -- as a source file in my repo, and/or in either of the two ways described above -- must that whole project me GPL-licensed?

To reiterate, my goal here is to respect your wishes about how your code is used. The choice of the GPL license signals to me that you want users of tooltipsy to share derivative works under the GPL, and I want to respect that choice. However, the GPL is quite unclear about what constitutes a derivative work in this situation, so I think you ought to clarify what _your_ definition is for purposes of your library.

Thank you!

**Comment by vitorbaptista** [comment]
@briancray Sorry to revive an old thread, but is that still the case? If so, it would be great to actually change the licensing notice in the files, as having a `LICENSE` file with MIT and a header with GPL2 is quite confusing (and creates legal insecurity)

**Comment by chooowai** [comment]
Hello, 
Where did i use the header with GPL2?

**Comment by vitorbaptista** [comment]
@briancray I received a comment by e-mail on this issue that was deleted. Not sure if it was you, but someone asked where there's a GPL2 license in this project.

It's in the comments inside the `.js` files, as:
https://github.com/briancray/tooltipsy/blob/master/tooltipsy.source.js#L2
https://github.com/briancray/tooltipsy/blob/master/tooltipsy.min.js#L2
