### ISSUE TITLE
Bower registry

### ISSUE THREAD

**Issue by ImBobby** [briancray/tooltipsy#35]
Hi @briancray, please consider to register this plugin to Bower registry.

**Comment by mvastola** [comment]
+1

**Comment by thiagofesta** [comment]
+1

**Comment by mvastola** [comment]
Just a gentle ping @briancray to see if this could be done.

**Comment by ImBobby** [comment]
fyi tooltipsy is now available in Bower but the endpoint is not here. The endpoint is directed to a [forked repo](https://github.com/jsbuzz/tooltipsy) and 2 commits behind from upstream.
